### Numpy

#### Import package

In [2]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,5],dtype='float32')

print(arr_1d)

[1. 2. 3. 4. 5.]


In [5]:
# 2D
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
type(arr_2d)

numpy.ndarray

In [8]:
arr_2d.shape

(3, 3)

In [9]:
arr_2d.ndim

2

In [10]:
arr_2d.dtype

dtype('int32')

In [ ]:
# no
arr_2d.size

9

In [ ]:
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones([2,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.full((4,6),0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.random.rand(4,5)

array([[0.38729186, 0.77494987, 0.37002652, 0.3575638 , 0.73252222],
       [0.82799975, 0.56336455, 0.09887857, 0.08726819, 0.91015388],
       [0.81776479, 0.43604203, 0.73886518, 0.40264601, 0.85226497],
       [0.63617317, 0.16740066, 0.37193349, 0.35034795, 0.03066676]])

In [21]:
np.random.random((4,5))

array([[0.00608193, 0.50867145, 0.82315912, 0.09857509, 0.41258682],
       [0.67172982, 0.96262587, 0.80428738, 0.43524129, 0.07705832],
       [0.76975358, 0.50159992, 0.63377608, 0.16020521, 0.92549023],
       [0.12417636, 0.75689317, 0.18036163, 0.14088073, 0.49310031]])

In [23]:
np.random.seed(42)
np.random.random((4,5))

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [36]:
np.random.seed(42)
np.random.random((4,5))

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [37]:
np.random.randint(0, 10, (4,5))

array([[9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4],
       [8, 6, 1, 3, 8],
       [1, 9, 8, 9, 4]])

In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [39]:
arr1 + arr2

array([5, 7, 9])

In [40]:
arr1 - arr2

array([-3, -3, -3])

In [41]:
arr1 * arr2

array([ 4, 10, 18])

In [42]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [45]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

In [ ]:
x = np.array([1,2,3])
 y = np.array([4,5,6])

In [47]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [60]:
x1 = np.array([[1,2,3]])
y1 = np.array([[4,5,6]])
np.concatenate((x1, y1), axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [62]:
z = np.array([[9,8,7],[6,5,4]])
t = np.array([[99],[99]])

In [63]:
np.vstack((x1,z))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [64]:
#x = 1 hang 3 cot (1x3), y =  3 hang 1 cot (3x1)
x2 = np.array([[11,22,33]])
y2 = np.array([[44],[55],[66]])

In [69]:
np.hstack((x1, y1))  # horizontal stack

array([[1, 2, 3, 4, 5, 6]])

In [70]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [71]:
a1, a2, a3 = np.split(a, [3,5])  # 3,5: indexes

In [72]:
a1

array([1, 2, 3])

In [73]:
a2

array([4, 5])

In [74]:
a3

array([6, 7, 8, 9])

In [75]:
arr = np.array([10, 20, 30, 40, 50])

In [76]:
arr[1:4]

array([20, 30, 40])

In [79]:
# Broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

In [81]:
result = arr1 + arr2
result

array([11, 22, 33])

In [82]:
 arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [84]:
result = arr_2d + arr1
result

array([[2, 4, 6],
       [5, 7, 9]])

In [85]:
arr = np.array([1, 2, 3, 4, 5])